// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bMtMmLyZOAxNBTWW08gq29FXbYk_qA4',
    appId: '1:917359166242:web:6890505796efd2c0d0db7b',
    messagingSenderId: '917359166242',
    projectId: 'veridis-app',
    authDomain: 'veridis-app.firebaseapp.com',
    storageBucket: 'veridis-app.firebasestorage.app',
    measurementId: 'G-0Q4YPB4W07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYK_bPR3e5Qve_zAdvenIimNeinORUWoc',
    appId: '1:917359166242:android:81a4772edcc56d96d0db7b',
    messagingSenderId: '917359166242',
    projectId: 'veridis-app',
    storageBucket: 'veridis-app.firebasestorage.app',
  );
}
